users:
  - suiyujin
  - hogehoge
zsh_users:
  - suiyujin
platform: redhat
rtn_git:
  version: 2.13.0
tmux:
  prefix: /usr/local
  version: 2.5
libevent:
  version: 2.1.8
mysql:
  password: hogepassword
rtn_rbenv:
  user: root
  versions:
    2.3.4:
      - bundler
      - pry
      - pry-doc
      - pry-byebug
  global: 2.3.4
